module.exports = {
  content: [
    "./index.html",
    "./*.{js,ts,jsx,tsx}",
    "./routes/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg': '#0a0a0f',
        'bg2': '#111118',
        'bg3': '#18181f',
        'accent': '#7c6bff',
        'accent2': '#4fffb8',
        'accent3': '#ff6b8a',
        'text': '#f0eeff',
        'muted': 'rgba(240,238,255,0.45)',
        'muted2': 'rgba(240,238,255,0.22)',
        // Aether Intelligence Design System
        'surface-container-high': '#2a292f',
        'primary': '#c6bfff',
        'background': '#131318',
        'surface': '#131318',
        'on-background': '#e4e1e9',
        'outline': '#928ea0',
        'on-error': '#690005',
        'surface-container': '#1f1f25',
        'on-tertiary-container': '#5a001f',
        'inverse-on-surface': '#303036',
        'on-surface-variant': '#c8c4d7',
        'text-primary': '#f0eeff',
        'surface-variant': '#35343a',
        'inverse-primary': '#5844d9',
        'primary-container': '#8d7fff',
        'secondary-fixed': '#4effb8',
        'secondary': '#46f9b2',
        'chart-yellow': '#ffd166',
        'outline-variant': '#474555',
        'border-bold': 'rgba(255,255,255,0.13)',
        'tertiary-container': '#ef5f7e',
        'border-subtle': 'rgba(255,255,255,0.07)',
        'on-secondary-container': '#005b3c',
        'surface-elevated': '#18181f',
        'surface-dim': '#131318',
        'on-surface': '#e4e1e9',
        'surface-container-highest': '#35343a',
        'tertiary': '#ffb2bd',
        'tertiary-fixed-dim': '#ffb2bd',
        'surface-core': '#111118',
        'surface-container-low': '#1b1b20',
        'surface-container-lowest': '#0e0e13',
        'on-tertiary-fixed': '#400013',
        'on-secondary': '#003824',
        'primary-fixed-dim': '#c6bfff',
        'text-muted': 'rgba(240,238,255,0.45)',
        'error': '#ffb4ab',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-fixed-variant': '#8c1037',
        'on-primary': '#29009f',
        'on-secondary-fixed': '#002113',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#23008d',
        'inverse-surface': '#e4e1e9',
        'on-tertiary': '#670024',
        'secondary-fixed-dim': '#1be19d',
        'on-primary-fixed-variant': '#4025c1',
        'primary-fixed': '#e4dfff',
        'error-container': '#93000a',
        'secondary-container': '#02dc98',
        'on-primary-fixed': '#170066',
        'surface-tint': '#c6bfff',
        'status-error': '#ff6b6b',
        'surface-bright': '#39383e',
        'tertiary-fixed': '#ffd9dd',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      spacing: {
        'gap-sm': '12px',
        'gap-lg': '48px',
        'gap-xs': '8px',
        'base': '4px',
        'section-h-desktop': '40px',
        'gap-md': '16px',
        'section-v-desktop': '100px',
        'container-max': '900px',
      },
      fontFamily: {
        'syne': ['Syne', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'body-lg': ['JetBrains Mono', 'monospace'],
        'hero-display-mobile': ['Syne', 'sans-serif'],
        'section-title': ['Syne', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'data-highlight': ['Syne', 'sans-serif'],
        'body-md': ['JetBrains Mono', 'monospace'],
        'hero-display': ['Syne', 'sans-serif'],
        'code-block': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['17px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['13px', { lineHeight: '1.4', fontWeight: '600' }],
        'section-title': ['42px', { lineHeight: '1.2', fontWeight: '800' }],
        'data-highlight': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      animation: {
        'fadeUp': 'fadeUp 0.7s ease-out forwards',
        'pulse-soft': 'pulse 2s infinite',
        'slide-in': 'slideIn 0.5s ease-out forwards',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateX(-10px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
}
